#!/usr/bin/env bash
# Generate the png2lvgl AUR PKGBUILD from the measured source tarball.
#
# The checksum is measured from the archive that GitHub actually serves for the
# release tag, so `makepkg` verifies the same bytes a user downloads. The
# previous checked-in PKGBUILD used sha256sums=('SKIP') and verified nothing.

set -euo pipefail

readonly PROGRAM='generate-pkgbuild'

fail() {
  local code="$1"
  shift
  printf '%s[%s]: %s\n' "$PROGRAM" "$code" "$*" >&2
  exit 1
}

sha256_of() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | cut -d ' ' -f 1
  else
    shasum -a 256 "$path" | cut -d ' ' -f 1
  fi
}

VERSION=''
URL=''
SOURCE_ARCHIVE=''
OUTPUT=''

while (( $# > 0 )); do
  case "$1" in
    --version) VERSION="${2-}"; shift 2 ;;
    --url) URL="${2-}"; shift 2 ;;
    --source-archive) SOURCE_ARCHIVE="${2-}"; shift 2 ;;
    --output) OUTPUT="${2-}"; shift 2 ;;
    *) fail PKB1001 "unknown argument: $1" ;;
  esac
done

[[ -n "$VERSION" ]] || fail PKB1002 '--version is required'
[[ -n "$URL" ]] || fail PKB1002 '--url is required'
[[ -n "$SOURCE_ARCHIVE" ]] || fail PKB1002 '--source-archive is required'
[[ -n "$OUTPUT" ]] || fail PKB1002 '--output is required'

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
  fail PKB1003 "version must be a bare release SemVer name: $VERSION"
[[ "$URL" =~ ^https://[^[:space:]?\#]+$ ]] ||
  fail PKB1004 "url must be HTTPS without whitespace, query or fragment: $URL"
[[ -f "$SOURCE_ARCHIVE" ]] ||
  fail PKB1005 "source archive does not exist: $SOURCE_ARCHIVE"

# A GitHub source tarball for a real tag is never this small. Guard against
# writing a checksum over an error page that was saved with a 200 status.
archive_bytes=$(wc -c < "$SOURCE_ARCHIVE" | tr -d ' ')
(( archive_bytes >= 4096 )) ||
  fail PKB1006 "source archive is implausibly small: ${archive_bytes} bytes"
# Materialise the listing instead of piping it into a reader that exits early.
# Under `set -o pipefail` a `tar | grep -q` pipeline reports failure whenever
# grep finds its match before tar has finished writing: tar then dies of
# SIGPIPE with status 141 and pipefail propagates that. The match position
# decides it, so the bug is a race that passes locally and fails in CI.
listing="$(mktemp)"
# shellcheck disable=SC2064
trap "rm -f '$listing'" EXIT
tar tzf "$SOURCE_ARCHIVE" > "$listing" 2>/dev/null ||
  fail PKB1007 "source archive is not a readable gzip tarball: $SOURCE_ARCHIVE"
if ! grep -Fxq "png2lvgl-${VERSION}/Cargo.toml" "$listing"; then
  printf '%s[PKB1008]: archive holds %s entries, first ten:\n' \
    "$PROGRAM" "$(wc -l < "$listing" | tr -d ' ')" >&2
  head -10 "$listing" >&2
  fail PKB1008 "source archive does not contain png2lvgl-${VERSION}/Cargo.toml"
fi

SOURCE_SHA="$(sha256_of "$SOURCE_ARCHIVE")"
[[ "$SOURCE_SHA" =~ ^[0-9a-f]{64}$ ]] ||
  fail PKB1009 "measured digest is malformed: $SOURCE_SHA"

install -d "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<PKGBUILD
# Generated by scripts/release/generate-pkgbuild.sh. Do not edit.
# Maintainer: metaneutrons <https://github.com/metaneutrons>
pkgname=png2lvgl
pkgver=${VERSION}
pkgrel=1
pkgdesc="Convert PNG images to LVGL C arrays"
arch=('x86_64' 'aarch64')
url="https://github.com/metaneutrons/png2lvgl"
license=('GPL-3.0-only')
depends=('gcc-libs' 'glibc')
makedepends=('cargo')
source=("\$pkgname-\$pkgver.tar.gz::${URL}")
sha256sums=('${SOURCE_SHA}')

prepare() {
    cd "\$pkgname-\$pkgver"
    export RUSTUP_TOOLCHAIN=stable
    cargo fetch --locked --target "\$(rustc -vV | sed -n 's/host: //p')"
}

build() {
    cd "\$pkgname-\$pkgver"
    export RUSTUP_TOOLCHAIN=stable
    export CARGO_TARGET_DIR=target
    cargo build --frozen --release
}

check() {
    cd "\$pkgname-\$pkgver"
    export RUSTUP_TOOLCHAIN=stable
    cargo test --frozen
}

package() {
    cd "\$pkgname-\$pkgver"
    install -Dm755 "target/release/\$pkgname" "\$pkgdir/usr/bin/\$pkgname"

    # clap_mangen writes the manpage into the build script output directory.
    # Resolve it explicitly so a missing manpage fails the package instead of
    # silently shipping without one.
    local manpage
    manpage=\$(find target/release/build -type f -name "\$pkgname.1" -print -quit)
    if [[ -z "\$manpage" ]]; then
        echo "generated manpage \$pkgname.1 not found" >&2
        return 1
    fi
    install -Dm644 "\$manpage" "\$pkgdir/usr/share/man/man1/\$pkgname.1"

    install -Dm644 LICENSE "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
    install -Dm644 README.md "\$pkgdir/usr/share/doc/\$pkgname/README.md"
}
PKGBUILD

bash -n "$OUTPUT" || fail PKB1010 "generated PKGBUILD is not valid shell: $OUTPUT"
printf '%s[PKB0000]: wrote %s for version %s (sha256 %s)\n' \
  "$PROGRAM" "$OUTPUT" "$VERSION" "$SOURCE_SHA"
