#!/usr/bin/env bash
# Generate the png2lvgl Homebrew formula from measured release archives.
#
# Every value in the formula is measured from an artifact that exists on disk.
# Nothing is carried over from a checked-in template, so the formula cannot
# drift away from the release it describes.

set -euo pipefail

readonly PROGRAM='generate-homebrew-formula'

fail() {
  local code="$1"
  shift
  printf '%s[%s]: %s\n' "$PROGRAM" "$code" "$*" >&2
  exit 1
}

sha256_of() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | cut -d ' ' -f 1
  else
    shasum -a 256 "$path" | cut -d ' ' -f 1
  fi
}

measured_archive() {
  local target="$1"
  local path="${CANDIDATE_DIR}/png2lvgl-${VERSION}-${target}.tar.gz"
  [[ -f "$path" ]] || fail HBF1010 "release archive is missing: $path"
  printf '%s' "$path"
}

VERSION=''
BASE_URL=''
CANDIDATE_DIR=''
OUTPUT=''

while (( $# > 0 )); do
  case "$1" in
    --version) VERSION="${2-}"; shift 2 ;;
    --base-url) BASE_URL="${2-}"; shift 2 ;;
    --candidate-dir) CANDIDATE_DIR="${2-}"; shift 2 ;;
    --output) OUTPUT="${2-}"; shift 2 ;;
    *) fail HBF1001 "unknown argument: $1" ;;
  esac
done

[[ -n "$VERSION" ]] || fail HBF1002 '--version is required'
[[ -n "$BASE_URL" ]] || fail HBF1002 '--base-url is required'
[[ -n "$CANDIDATE_DIR" ]] || fail HBF1002 '--candidate-dir is required'
[[ -n "$OUTPUT" ]] || fail HBF1002 '--output is required'

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ ]] ||
  fail HBF1003 "version must be a bare SemVer name without a leading v: $VERSION"
[[ "$BASE_URL" =~ ^https?://[^[:space:]?\#]+$ ]] ||
  fail HBF1004 "base-url must be a URL without whitespace, query or fragment: $BASE_URL"
[[ -d "$CANDIDATE_DIR" ]] ||
  fail HBF1005 "candidate directory does not exist: $CANDIDATE_DIR"

BASE_URL="${BASE_URL%/}"

arm_archive="$(measured_archive aarch64-apple-darwin)"
intel_archive="$(measured_archive x86_64-apple-darwin)"
arm_sha="$(sha256_of "$arm_archive")"
intel_sha="$(sha256_of "$intel_archive")"

for digest in "$arm_sha" "$intel_sha"; do
  [[ "$digest" =~ ^[0-9a-f]{64}$ ]] || fail HBF1011 "measured digest is malformed: $digest"
done

install -d "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<FORMULA
# Generated by scripts/release/generate-homebrew-formula.sh. Do not edit.
class Png2lvgl < Formula
  desc "Convert PNG images to LVGL C arrays"
  homepage "https://github.com/metaneutrons/png2lvgl"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/$(basename "$arm_archive")"
      sha256 "${arm_sha}"
    else
      url "${BASE_URL}/$(basename "$intel_archive")"
      sha256 "${intel_sha}"
    end
  end

  def install
    bin.install "png2lvgl"
    man1.install "share/man/man1/png2lvgl.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/png2lvgl --version")
    system bin/"png2lvgl", "--help"
  end
end
FORMULA

printf '%s[HBF0000]: wrote %s for version %s\n' "$PROGRAM" "$OUTPUT" "$VERSION"
