// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2025 Fabian Schmieder

use std::io::Write;

use image::{DynamicImage, Rgba};
use tracing::{debug, instrument};

use crate::error::{FormatError, Result};
use crate::format::{ColorFormat, LvglVersion};

/// Number of bytes per line in the hex data array output.
const HEX_BYTES_PER_LINE: usize = 16;

/// Bytes per palette entry (RGBA32).
const PALETTE_ENTRY_SIZE: usize = 4;

/// RGB565 bit masks and shifts.
const RGB565_RED_MASK: u16 = 0xF8;
const RGB565_GREEN_MASK: u16 = 0xFC;
const RGB565_RED_SHIFT: u16 = 8;
const RGB565_GREEN_SHIFT: u16 = 3;
const RGB565_BLUE_SHIFT: u16 = 3;

/// Bits in a byte.
const BITS_PER_BYTE: u8 = 8;

#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Parameters for C code generation, avoiding excessive function arguments.
pub struct GenerateParams<'a> {
    pub var_name: &'a str,
    pub format: &'a ColorFormat,
    pub lvgl_version: LvglVersion,
    pub big_endian: bool,
    pub source_file: &'a str,
    pub output_file: &'a str,
}

/// Generate the complete LVGL C file for the given image.
#[instrument(skip(img, writer, params), fields(format = ?params.format, var_name = params.var_name))]
pub fn generate<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    params: &GenerateParams<'_>,
) -> Result<()> {
    debug!(?params.lvgl_version, "Generating C code");
    write_header(writer, params)?;

    let format_const = params.format.lvgl_const(params.lvgl_version);

    match params.format {
        ColorFormat::Indexed1
        | ColorFormat::Indexed2
        | ColorFormat::Indexed4
        | ColorFormat::Indexed8 => {
            let bpp = params.format.bpp().expect("indexed format must have bpp");
            write_indexed(
                img,
                writer,
                params.var_name,
                format_const,
                bpp,
                params.lvgl_version,
            )?;
        }
        ColorFormat::Alpha1 | ColorFormat::Alpha2 | ColorFormat::Alpha4 | ColorFormat::Alpha8 => {
            let bpp = params.format.bpp().expect("alpha format must have bpp");
            write_alpha(
                img,
                writer,
                params.var_name,
                format_const,
                bpp,
                params.lvgl_version,
            )?;
        }
        ColorFormat::TrueColor | ColorFormat::TrueColorAlpha => {
            write_true_color(
                img,
                writer,
                params.var_name,
                params.format.has_alpha(),
                format_const,
                params.big_endian,
                params.lvgl_version,
            )?;
        }
        ColorFormat::TrueColorChroma => {
            return Err(FormatError::NotImplemented {
                format: "TrueColorChroma".to_string(),
            }
            .into());
        }
        ColorFormat::Auto => unreachable!("Auto should be resolved before codegen"),
    }

    debug!("C code generation complete");
    Ok(())
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

fn write_header<W: Write>(writer: &mut W, params: &GenerateParams<'_>) -> Result<()> {
    let version = built_info::GIT_VERSION.unwrap_or(built_info::PKG_VERSION);
    let lvgl_ver = match params.lvgl_version {
        LvglVersion::V8 => "LVGL 8.x",
        LvglVersion::V9 => "LVGL 9.x",
    };

    writeln!(writer, "/**")?;
    writeln!(
        writer,
        " * {} - LVGL image asset of {}",
        params.output_file, params.source_file
    )?;
    writeln!(writer, " * ")?;
    writeln!(
        writer,
        " * Generated by png2lvgl v{version} (https://github.com/metaneutrons/png2lvgl)"
    )?;
    writeln!(writer, " * ")?;
    writeln!(writer, " * DO NOT EDIT THIS FILE MANUALLY")?;
    writeln!(writer, " * ")?;
    writeln!(writer, " * Target: {lvgl_ver}")?;
    writeln!(writer, " * Format: {}", params.format.description())?;

    if params.format.is_rgb565() {
        let order = if params.big_endian {
            "big-endian"
        } else {
            "little-endian"
        };
        writeln!(writer, " * RGB565 Byte Order: {order}")?;
    }

    writeln!(writer, " */")?;
    writeln!(writer)?;

    write!(
        writer,
        "\
#ifdef __has_include
    #if __has_include(\"lvgl.h\")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include \"lvgl.h\"
#else
    #include \"lvgl/lvgl.h\"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_{upper_var}
#define LV_ATTRIBUTE_IMG_{upper_var}
#endif

",
        upper_var = params.var_name.to_uppercase()
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Pixel bit-packing (shared by indexed + alpha formats)
// ---------------------------------------------------------------------------

/// Pack pixel values into bytes, MSB-first, row by row.
fn pack_pixels_msb(
    width: u32,
    height: u32,
    bpp: u8,
    pixel_value: impl Fn(u32, u32) -> u8,
) -> Vec<u8> {
    let mask = (1u8 << bpp) - 1;
    let mut data = Vec::new();

    for y in 0..height {
        let mut byte = 0u8;
        let mut shift = BITS_PER_BYTE - bpp;

        for x in 0..width {
            let value = (pixel_value(x, y) >> (BITS_PER_BYTE - bpp)) & mask;
            byte |= value << shift;

            if shift == 0 {
                data.push(byte);
                byte = 0;
                shift = BITS_PER_BYTE - bpp;
            } else {
                shift -= bpp;
            }
        }

        // Flush partial byte at end of row
        if shift != BITS_PER_BYTE - bpp {
            data.push(byte);
        }
    }

    data
}

// ---------------------------------------------------------------------------
// Format writers
// ---------------------------------------------------------------------------

#[instrument(skip(img, writer))]
fn write_indexed<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    format_const: &str,
    bpp: u8,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let gray = img.to_luma8();
    let (width, height) = gray.dimensions();
    let palette_size: usize = 1 << bpp;
    debug!(width, height, bpp, "Writing indexed data");

    write_array_open(writer, var_name)?;

    // Palette (RGBA32)
    for i in 0..palette_size {
        #[allow(clippy::cast_possible_truncation)]
        let val = (i * 255 / (palette_size - 1)) as u8;
        writeln!(
            writer,
            "  0x{val:02x}, 0x{val:02x}, 0x{val:02x}, 0xff, \t/*Color of index {i}*/"
        )?;
    }
    writeln!(writer)?;

    let data = pack_pixels_msb(width, height, bpp, |x, y| gray.get_pixel(x, y)[0]);

    write_data_array(writer, &data)?;
    writeln!(writer, "}};\n")?;

    let total_size = palette_size * PALETTE_ENTRY_SIZE + data.len();
    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        total_size,
        lvgl_version,
    )?;
    Ok(())
}

#[instrument(skip(img, writer))]
fn write_true_color<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    alpha: bool,
    format_const: &str,
    big_endian: bool,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let rgba = img.to_rgba8();
    let (width, height) = rgba.dimensions();
    debug!(width, height, alpha, big_endian, "Writing true color data");

    write_array_open(writer, var_name)?;

    let mut rgb_data = Vec::new();
    let mut alpha_data = Vec::new();

    for pixel in rgba.pixels() {
        let Rgba(channels) = *pixel;
        let rgb565 = encode_rgb565(channels[0], channels[1], channels[2]);

        #[allow(clippy::cast_possible_truncation)]
        let hi = (rgb565 >> 8) as u8;
        #[allow(clippy::cast_possible_truncation)]
        let lo = (rgb565 & 0xFF) as u8;

        if big_endian {
            rgb_data.push(hi);
            rgb_data.push(lo);
        } else {
            rgb_data.push(lo);
            rgb_data.push(hi);
        }

        if alpha {
            alpha_data.push(channels[3]);
        }
    }

    write_data_array(writer, &rgb_data)?;
    if alpha {
        writeln!(writer)?;
        write_data_array(writer, &alpha_data)?;
    }
    writeln!(writer, "}};\n")?;

    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        rgb_data.len() + alpha_data.len(),
        lvgl_version,
    )?;
    Ok(())
}

#[instrument(skip(img, writer))]
fn write_alpha<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    format_const: &str,
    bpp: u8,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let gray = img.to_luma8();
    let (width, height) = gray.dimensions();
    debug!(width, height, bpp, "Writing alpha data");

    write_array_open(writer, var_name)?;

    let data = if bpp == BITS_PER_BYTE {
        gray.pixels().map(|p| p[0]).collect()
    } else {
        pack_pixels_msb(width, height, bpp, |x, y| gray.get_pixel(x, y)[0])
    };

    write_data_array(writer, &data)?;
    writeln!(writer, "}};\n")?;

    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        data.len(),
        lvgl_version,
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Encode an RGB pixel to RGB565.
const fn encode_rgb565(red: u8, green: u8, blue: u8) -> u16 {
    ((red as u16 & RGB565_RED_MASK) << RGB565_RED_SHIFT)
        | ((green as u16 & RGB565_GREEN_MASK) << RGB565_GREEN_SHIFT)
        | (blue as u16 >> RGB565_BLUE_SHIFT)
}

fn write_array_open<W: Write>(writer: &mut W, var_name: &str) -> Result<()> {
    writeln!(
        writer,
        "const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST \
         LV_ATTRIBUTE_IMG_{upper} uint8_t {var_name}_map[] = {{",
        upper = var_name.to_uppercase()
    )?;
    Ok(())
}

fn write_data_array<W: Write>(writer: &mut W, data: &[u8]) -> Result<()> {
    for (i, chunk) in data.chunks(HEX_BYTES_PER_LINE).enumerate() {
        if i > 0 {
            writeln!(writer)?;
        }
        write!(writer, "  ")?;
        for (j, byte) in chunk.iter().enumerate() {
            if j > 0 {
                write!(writer, ", ")?;
            }
            write!(writer, "0x{byte:02x}")?;
        }
        write!(writer, ",")?;
    }
    writeln!(writer)?;
    Ok(())
}

fn write_descriptor<W: Write>(
    writer: &mut W,
    var_name: &str,
    width: u32,
    height: u32,
    cf: &str,
    size: usize,
    lvgl_version: LvglVersion,
) -> Result<()> {
    writeln!(writer, "const lv_img_dsc_t {var_name} = {{")?;
    writeln!(writer, "  .header.cf = {cf},")?;

    if matches!(lvgl_version, LvglVersion::V8) {
        writeln!(writer, "  .header.always_zero = 0,")?;
        writeln!(writer, "  .header.reserved = 0,")?;
    }

    writeln!(writer, "  .header.w = {width},")?;
    writeln!(writer, "  .header.h = {height},")?;
    writeln!(writer, "  .data_size = {size},")?;
    writeln!(writer, "  .data = {var_name}_map,")?;
    writeln!(writer, "}};")?;
    Ok(())
}
