// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025 Fabian Schmieder

use std::io::Write;

use image::{DynamicImage, Rgba};
use tracing::{debug, instrument};

use crate::error::{FormatError, Result};
use crate::format::{ColorFormat, LvglVersion};

/// Number of bytes per line in the hex data array output.
const HEX_BYTES_PER_LINE: usize = 16;

/// Bytes per palette entry (RGBA32).
const PALETTE_ENTRY_SIZE: usize = 4;

/// RGB565 bit masks and shifts.
const RGB565_RED_MASK: u16 = 0xF8;
const RGB565_GREEN_MASK: u16 = 0xFC;
const RGB565_RED_SHIFT: u16 = 8;
const RGB565_GREEN_SHIFT: u16 = 3;
const RGB565_BLUE_SHIFT: u16 = 3;

/// Bits in a byte.
const BITS_PER_BYTE: u8 = 8;

#[allow(clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Parameters for C code generation, avoiding excessive function arguments.
pub struct GenerateParams<'a> {
    pub var_name: &'a str,
    pub format: &'a ColorFormat,
    pub lvgl_version: LvglVersion,
    pub big_endian: bool,
    pub source_file: &'a str,
    pub output_file: &'a str,
}

/// Generate the complete LVGL C file for the given image.
#[instrument(skip(img, writer, params), fields(format = ?params.format, var_name = params.var_name))]
pub fn generate<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    params: &GenerateParams<'_>,
) -> Result<()> {
    debug!(?params.lvgl_version, "Generating C code");
    write_header(writer, params)?;

    let format_const = params.format.lvgl_const(params.lvgl_version);

    match params.format {
        ColorFormat::Indexed1
        | ColorFormat::Indexed2
        | ColorFormat::Indexed4
        | ColorFormat::Indexed8 => {
            let bpp = params.format.bpp().expect("indexed format must have bpp");
            write_indexed(
                img,
                writer,
                params.var_name,
                format_const,
                bpp,
                params.lvgl_version,
            )?;
        }
        ColorFormat::Alpha1 | ColorFormat::Alpha2 | ColorFormat::Alpha4 | ColorFormat::Alpha8 => {
            let bpp = params.format.bpp().expect("alpha format must have bpp");
            write_alpha(
                img,
                writer,
                params.var_name,
                format_const,
                bpp,
                params.lvgl_version,
            )?;
        }
        ColorFormat::TrueColor | ColorFormat::TrueColorAlpha => {
            write_true_color(
                img,
                writer,
                params.var_name,
                params.format.has_alpha(),
                format_const,
                params.big_endian,
                params.lvgl_version,
            )?;
        }
        ColorFormat::TrueColorChroma => {
            return Err(FormatError::NotImplemented {
                format: "TrueColorChroma".to_string(),
            }
            .into());
        }
        ColorFormat::Auto => unreachable!("Auto should be resolved before codegen"),
    }

    debug!("C code generation complete");
    Ok(())
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

fn write_header<W: Write>(writer: &mut W, params: &GenerateParams<'_>) -> Result<()> {
    let version = built_info::PKG_VERSION;
    let lvgl_ver = match params.lvgl_version {
        LvglVersion::V8 => "LVGL 8.x",
        LvglVersion::V9 => "LVGL 9.x",
    };

    writeln!(writer, "/**")?;
    writeln!(
        writer,
        " * {} - LVGL image asset of {}",
        params.output_file, params.source_file
    )?;
    writeln!(writer, " * ")?;
    writeln!(
        writer,
        " * Generated by png2lvgl v{version} (https://github.com/metaneutrons/png2lvgl)"
    )?;
    writeln!(writer, " * ")?;
    writeln!(writer, " * DO NOT EDIT THIS FILE MANUALLY")?;
    writeln!(writer, " * ")?;
    writeln!(writer, " * Target: {lvgl_ver}")?;
    writeln!(writer, " * Format: {}", params.format.description())?;

    if params.format.is_rgb565() {
        let order = if params.big_endian {
            "big-endian"
        } else {
            "little-endian"
        };
        writeln!(writer, " * RGB565 Byte Order: {order}")?;
    }

    writeln!(writer, " */")?;
    writeln!(writer)?;

    write!(
        writer,
        "\
#ifdef __has_include
    #if __has_include(\"lvgl.h\")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include \"lvgl.h\"
#else
    #include \"lvgl/lvgl.h\"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_{upper_var}
#define LV_ATTRIBUTE_IMG_{upper_var}
#endif

",
        upper_var = params.var_name.to_uppercase()
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Pixel bit-packing (shared by indexed + alpha formats)
// ---------------------------------------------------------------------------

/// Pack pixel values into bytes, MSB-first, row by row.
fn pack_pixels_msb(
    width: u32,
    height: u32,
    bpp: u8,
    pixel_value: impl Fn(u32, u32) -> u8,
) -> Vec<u8> {
    // Derived by shifting down, not up: `1u8 << 8` overflows, which made the
    // mask 0 in a release build, so every 8 bpp pixel packed to zero, while a
    // debug build panicked outright. Shifting `u8::MAX` down is exact for every
    // bpp from 1 to 8.
    let mask = u8::MAX >> (BITS_PER_BYTE - bpp);
    let mut data = Vec::new();

    for y in 0..height {
        let mut byte = 0u8;
        let mut shift = BITS_PER_BYTE - bpp;

        for x in 0..width {
            let value = (pixel_value(x, y) >> (BITS_PER_BYTE - bpp)) & mask;
            byte |= value << shift;

            if shift == 0 {
                data.push(byte);
                byte = 0;
                shift = BITS_PER_BYTE - bpp;
            } else {
                shift -= bpp;
            }
        }

        // Flush partial byte at end of row
        if shift != BITS_PER_BYTE - bpp {
            data.push(byte);
        }
    }

    data
}

// ---------------------------------------------------------------------------
// Format writers
// ---------------------------------------------------------------------------

#[instrument(skip(img, writer))]
fn write_indexed<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    format_const: &str,
    bpp: u8,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let gray = img.to_luma8();
    let (width, height) = gray.dimensions();
    let palette_size: usize = 1 << bpp;
    debug!(width, height, bpp, "Writing indexed data");

    write_array_open(writer, var_name)?;

    // Palette (RGBA32)
    for i in 0..palette_size {
        #[allow(clippy::cast_possible_truncation)]
        let val = (i * 255 / (palette_size - 1)) as u8;
        writeln!(
            writer,
            "  0x{val:02x}, 0x{val:02x}, 0x{val:02x}, 0xff, \t/*Color of index {i}*/"
        )?;
    }
    writeln!(writer)?;

    let data = pack_pixels_msb(width, height, bpp, |x, y| gray.get_pixel(x, y)[0]);

    write_data_array(writer, &data)?;
    writeln!(writer, "}};\n")?;

    let total_size = palette_size * PALETTE_ENTRY_SIZE + data.len();
    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        total_size,
        lvgl_version,
    )?;
    Ok(())
}

#[instrument(skip(img, writer))]
fn write_true_color<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    alpha: bool,
    format_const: &str,
    big_endian: bool,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let rgba = img.to_rgba8();
    let (width, height) = rgba.dimensions();
    debug!(width, height, alpha, big_endian, "Writing true color data");

    write_array_open(writer, var_name)?;

    let mut rgb_data = Vec::new();
    let mut alpha_data = Vec::new();

    for pixel in rgba.pixels() {
        let Rgba(channels) = *pixel;
        let rgb565 = encode_rgb565(channels[0], channels[1], channels[2]);

        #[allow(clippy::cast_possible_truncation)]
        let hi = (rgb565 >> 8) as u8;
        #[allow(clippy::cast_possible_truncation)]
        let lo = (rgb565 & 0xFF) as u8;

        if big_endian {
            rgb_data.push(hi);
            rgb_data.push(lo);
        } else {
            rgb_data.push(lo);
            rgb_data.push(hi);
        }

        if alpha {
            alpha_data.push(channels[3]);
        }
    }

    write_data_array(writer, &rgb_data)?;
    if alpha {
        writeln!(writer)?;
        write_data_array(writer, &alpha_data)?;
    }
    writeln!(writer, "}};\n")?;

    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        rgb_data.len() + alpha_data.len(),
        lvgl_version,
    )?;
    Ok(())
}

#[instrument(skip(img, writer))]
fn write_alpha<W: Write>(
    img: &DynamicImage,
    writer: &mut W,
    var_name: &str,
    format_const: &str,
    bpp: u8,
    lvgl_version: LvglVersion,
) -> Result<()> {
    let gray = img.to_luma8();
    let (width, height) = gray.dimensions();
    debug!(width, height, bpp, "Writing alpha data");

    write_array_open(writer, var_name)?;

    // No special case for 8 bpp any more. It existed only to route around the
    // overflowing mask above, and it hid the defect from the alpha formats
    // while the indexed ones ran into it.
    let data = pack_pixels_msb(width, height, bpp, |x, y| gray.get_pixel(x, y)[0]);

    write_data_array(writer, &data)?;
    writeln!(writer, "}};\n")?;

    write_descriptor(
        writer,
        var_name,
        width,
        height,
        format_const,
        data.len(),
        lvgl_version,
    )?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Encode an RGB pixel to RGB565.
const fn encode_rgb565(red: u8, green: u8, blue: u8) -> u16 {
    ((red as u16 & RGB565_RED_MASK) << RGB565_RED_SHIFT)
        | ((green as u16 & RGB565_GREEN_MASK) << RGB565_GREEN_SHIFT)
        | (blue as u16 >> RGB565_BLUE_SHIFT)
}

fn write_array_open<W: Write>(writer: &mut W, var_name: &str) -> Result<()> {
    writeln!(
        writer,
        "const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST \
         LV_ATTRIBUTE_IMG_{upper} uint8_t {var_name}_map[] = {{",
        upper = var_name.to_uppercase()
    )?;
    Ok(())
}

fn write_data_array<W: Write>(writer: &mut W, data: &[u8]) -> Result<()> {
    for (i, chunk) in data.chunks(HEX_BYTES_PER_LINE).enumerate() {
        if i > 0 {
            writeln!(writer)?;
        }
        write!(writer, "  ")?;
        for (j, byte) in chunk.iter().enumerate() {
            if j > 0 {
                write!(writer, ", ")?;
            }
            write!(writer, "0x{byte:02x}")?;
        }
        write!(writer, ",")?;
    }
    writeln!(writer)?;
    Ok(())
}

fn write_descriptor<W: Write>(
    writer: &mut W,
    var_name: &str,
    width: u32,
    height: u32,
    cf: &str,
    size: usize,
    lvgl_version: LvglVersion,
) -> Result<()> {
    writeln!(writer, "const lv_img_dsc_t {var_name} = {{")?;
    writeln!(writer, "  .header.cf = {cf},")?;

    if matches!(lvgl_version, LvglVersion::V8) {
        writeln!(writer, "  .header.always_zero = 0,")?;
        writeln!(writer, "  .header.reserved = 0,")?;
    }

    writeln!(writer, "  .header.w = {width},")?;
    writeln!(writer, "  .header.h = {height},")?;
    writeln!(writer, "  .data_size = {size},")?;
    writeln!(writer, "  .data = {var_name}_map,")?;
    writeln!(writer, "}};")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use image::{DynamicImage, GrayImage, Luma, Rgb, RgbImage, Rgba, RgbaImage};

    use super::{ColorFormat, GenerateParams, LvglVersion, built_info, generate, pack_pixels_msb};

    fn solid_rgb(width: u32, height: u32, color: [u8; 3]) -> DynamicImage {
        let mut img = RgbImage::new(width, height);
        for pixel in img.pixels_mut() {
            *pixel = Rgb(color);
        }
        DynamicImage::ImageRgb8(img)
    }

    fn two_colors() -> DynamicImage {
        let img = RgbImage::from_fn(2, 1, |x, _| {
            if x == 0 {
                Rgb([0, 0, 0])
            } else {
                Rgb([255, 255, 255])
            }
        });
        DynamicImage::ImageRgb8(img)
    }

    fn render(
        img: &DynamicImage,
        format: &ColorFormat,
        version: LvglVersion,
        big_endian: bool,
    ) -> String {
        let mut out = Vec::new();
        let params = GenerateParams {
            var_name: "asset",
            format,
            lvgl_version: version,
            big_endian,
            source_file: "input.png",
            output_file: "output.c",
        };
        generate(img, &mut out, &params).expect("generate");
        String::from_utf8(out).expect("generated C must be valid UTF-8")
    }

    /// Up to and including v0.3.5 the header carried the git describe output,
    /// so a release build wrote a bare commit hash here and a tagged build the
    /// doubled `vv0.3.5`. It must be the package version, exactly once.
    #[test]
    fn header_states_the_package_version() {
        let text = render(
            &solid_rgb(1, 1, [0, 0, 0]),
            &ColorFormat::TrueColor,
            LvglVersion::V9,
            false,
        );
        let expected = format!("Generated by png2lvgl v{} ", built_info::PKG_VERSION);
        assert!(
            text.contains(&expected),
            "header does not carry the package version:\n{text}"
        );
        assert!(!text.contains("vv"), "version is prefixed twice:\n{text}");
    }

    #[test]
    fn header_names_the_target_and_the_format() {
        let v8 = render(
            &solid_rgb(1, 1, [0, 0, 0]),
            &ColorFormat::TrueColor,
            LvglVersion::V8,
            false,
        );
        assert!(v8.contains("Target: LVGL 8.x"), "{v8}");
        assert!(v8.contains("Format: RGB565 true color"), "{v8}");

        let v9 = render(
            &solid_rgb(1, 1, [0, 0, 0]),
            &ColorFormat::TrueColor,
            LvglVersion::V9,
            false,
        );
        assert!(v9.contains("Target: LVGL 9.x"), "{v9}");
    }

    /// The v8 descriptor carries two fields that v9 dropped. Emitting them into
    /// a v9 file breaks the build at the consumer.
    #[test]
    fn descriptor_matches_the_target_version() {
        let img = solid_rgb(2, 2, [255, 0, 0]);

        let v8 = render(&img, &ColorFormat::TrueColor, LvglVersion::V8, false);
        assert!(v8.contains("LV_IMG_CF_TRUE_COLOR"), "{v8}");
        assert!(v8.contains(".header.always_zero = 0,"), "{v8}");
        assert!(v8.contains(".header.reserved = 0,"), "{v8}");

        let v9 = render(&img, &ColorFormat::TrueColor, LvglVersion::V9, false);
        assert!(v9.contains("LV_COLOR_FORMAT_RGB565"), "{v9}");
        assert!(!v9.contains("always_zero"), "{v9}");
        assert!(!v9.contains(".header.reserved"), "{v9}");
    }

    #[test]
    fn descriptor_reports_the_image_dimensions() {
        let text = render(
            &solid_rgb(7, 3, [0, 0, 255]),
            &ColorFormat::TrueColor,
            LvglVersion::V9,
            false,
        );
        assert!(text.contains(".header.w = 7,"), "{text}");
        assert!(text.contains(".header.h = 3,"), "{text}");
    }

    #[test]
    fn variable_name_is_used_for_both_symbols() {
        let text = render(
            &solid_rgb(1, 1, [0, 0, 0]),
            &ColorFormat::TrueColor,
            LvglVersion::V9,
            false,
        );
        assert!(text.contains("const lv_img_dsc_t asset = {"), "{text}");
        assert!(text.contains("asset_map"), "{text}");
    }

    /// Pure red is 0xF800 in RGB565. The two byte orders must therefore differ,
    /// and the endianness must be recorded in the header.
    #[test]
    fn rgb565_byte_order_is_honoured() {
        let img = solid_rgb(1, 1, [255, 0, 0]);

        let little = render(&img, &ColorFormat::TrueColor, LvglVersion::V9, false);
        let big = render(&img, &ColorFormat::TrueColor, LvglVersion::V9, true);

        assert!(little.contains("little-endian"), "{little}");
        assert!(big.contains("big-endian"), "{big}");
        assert_ne!(little, big, "byte order had no effect on the output");
        assert!(
            little.contains("0x00, 0xf8"),
            "expected little-endian 0xF800:\n{little}"
        );
        assert!(
            big.contains("0xf8, 0x00"),
            "expected big-endian 0xF800:\n{big}"
        );
    }

    #[test]
    fn indexed_output_carries_a_palette() {
        let text = render(
            &two_colors(),
            &ColorFormat::Indexed1,
            LvglVersion::V9,
            false,
        );
        assert!(text.contains("LV_COLOR_FORMAT_I1"), "{text}");
        assert!(text.contains("1-bit indexed"), "{text}");
    }

    #[test]
    fn alpha_only_output_uses_the_alpha_constant() {
        let img = RgbaImage::from_fn(2, 2, |x, _| {
            Rgba([0, 0, 0, u8::try_from(x * 100).unwrap_or(0)])
        });
        let text = render(
            &DynamicImage::ImageRgba8(img),
            &ColorFormat::Alpha8,
            LvglVersion::V9,
            false,
        );
        assert!(text.contains("LV_COLOR_FORMAT_A8"), "{text}");
        assert!(text.contains("8-bit alpha"), "{text}");
    }

    /// Guards the C syntax at the coarsest level: unbalanced braces mean the
    /// consumer's build fails, and that is worth catching here rather than there.
    #[test]
    fn generated_c_has_balanced_braces() {
        for version in [LvglVersion::V8, LvglVersion::V9] {
            let text = render(
                &solid_rgb(3, 2, [1, 2, 3]),
                &ColorFormat::TrueColorAlpha,
                version,
                false,
            );
            let open = text.matches('{').count();
            let close = text.matches('}').count();
            assert_eq!(open, close, "unbalanced braces for {version:?}:\n{text}");
            assert!(
                text.trim_end().ends_with("};"),
                "file does not end with a declaration"
            );
        }
    }

    fn luma_row(values: &[u8]) -> DynamicImage {
        #[allow(clippy::cast_possible_truncation)]
        let width = values.len() as u32;
        DynamicImage::ImageLuma8(GrayImage::from_fn(width, 1, |x, _| {
            Luma([values[x as usize]])
        }))
    }

    /// `1u8 << 8` overflows. The mask therefore came out as 0 in a release
    /// build, so every 8 bpp pixel packed to zero, and a debug build panicked
    /// instead. Only the indexed path reached this: the alpha path used to
    /// route around it with a special case of its own.
    #[test]
    fn eight_bits_per_pixel_pass_through_unchanged() {
        let values = [50u8, 100, 150, 200];
        let packed = pack_pixels_msb(4, 1, 8, |x, _| values[x as usize]);
        assert_eq!(packed, values, "8 bpp must not alter the pixel");
    }

    /// The mask is now derived by shifting down. Guard that this still packs
    /// several pixels per byte for the sub-byte depths.
    #[test]
    fn four_bits_per_pixel_pack_two_to_a_byte() {
        let packed = pack_pixels_msb(2, 1, 4, |x, _| if x == 0 { 0xA0 } else { 0xB0 });
        assert_eq!(
            packed,
            [0xAB],
            "two 4 bpp pixels share one byte, high one first"
        );
    }

    /// Each row starts on a byte boundary, so a row that does not fill its last
    /// byte is flushed with the remaining bits left at zero.
    #[test]
    fn a_partial_row_is_flushed() {
        let packed = pack_pixels_msb(3, 1, 2, |_, _| 0xC0);
        assert_eq!(
            packed,
            [0b1111_1100],
            "three 2 bpp pixels fill six bits; the remaining two stay zero"
        );
    }

    /// The whole point, seen from outside: indexed8 used to emit an all-zero
    /// data array, which renders as a black image.
    #[test]
    fn indexed8_writes_the_pixel_values() {
        let text = render(
            &luma_row(&[50, 100, 150, 200]),
            &ColorFormat::Indexed8,
            LvglVersion::V9,
            false,
        );
        assert!(
            text.contains("0x32, 0x64, 0x96, 0xc8,"),
            "indexed8 lost the pixel values:\n{text}"
        );
    }
}
